version: "3.1"
services:
  config_server:
    image: hyness/spring-cloud-config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
  consul:
    image: consul:1.1.0
    hostname: localhost
    ports:
      - "8500:8500"
  eureka:
    build:
      context: eureka/.
    ports:
      - "8761:8761"
  wildfly:
    build:
      context: .
    ports:
      - "9990:9990"
  hr-service:
    image: hr:0.0.1-SNAPSHOT
  hr-proxy-service:
    image: hrhttpproxy:0.0.1-SNAPSHOT
    environment:
      HOST: hr-proxy-service
  hr-proxy-service-1:
    image: hrhttpproxy:0.0.1-SNAPSHOT
    environment:
      HOST: hr-proxy-service-1
  hr-proxy-service-2:
    image: hrhttpproxy:0.0.1-SNAPSHOT
    environment:
      HOST: hr-proxy-service-2
  mule:
    build:
      context: muleesb
    ports:
      - "8081:8081"
  spring-cloud-gateway:
    build:
      context: gateway/.
    ports:
      - "9912:9912"
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: soa
      POSTGRES_DB: soa
#    ports:
#      - "5432:5432"