version: "3.1"
services:
  config_server:
    image: hyness/spring-cloud-config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
  consul:
    image: consul:1.1.0
    hostname: localhost
    ports:
      - "8500:8500"
  eureka:
    build:
      context: eureka/.
    ports:
      - "8761:8761"
  wildfly:
    build:
      context: .
    ports:
      - "8080:8080"
      - "9990:9990"
  hr-service:
    build:
      context: hr/.
    environment:
      HOST: hr-service-1
    ports:
      - "8081:8081"
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: soa
      POSTGRES_DB: soa
    ports:
      - "5432:5432"