//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.11 at 01:33:56 AM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soa.yank0vy3rdna.ru/services/hr")
package ru.yank0vy3rdna.soa.lab3.hrhttpproxy.xsd;
